# Generated by Django 3.2.7 on 2021-09-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=85)),
                ('precio', models.CharField(max_length=90)),
                ('stock', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'helados',
            },
        ),
    ]
