# Generated by Django 3.2.7 on 2021-10-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concesionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=70)),
                ('ciudad', models.CharField(max_length=80)),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad_vehiculos', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('renta', models.CharField(max_length=80)),
                ('cordinador', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'concesionario',
            },
        ),
    ]
