# Generated by Django 3.2.7 on 2021-09-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=70)),
                ('marca', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=80)),
                ('precio', models.CharField(max_length=70)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'vehiculos',
            },
        ),
    ]
