# Generated by Django 3.2.7 on 2021-09-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('productoName', models.CharField(max_length=80)),
                ('precio', models.CharField(max_length=75)),
                ('stock', models.CharField(max_length=40)),
                ('unidad', models.IntegerField()),
                ('descuento', models.CharField(max_length=30)),
                ('total', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
