# Generated by Django 3.2.7 on 2021-09-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=80)),
                ('empresa', models.CharField(max_length=80)),
                ('estatus', models.IntegerField()),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
